server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          #rama donde se guarda
          default-label: config-server
          uri: https://github.com/derafaven/java-microservicios_simples_sprintCloud
          #archivo de configuracion de microservicios
          search-paths: config-data
  application:
    #nombre del servicio
    name: config-service
